# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

TOP = ..

USER_LIB_PATH = $(TOP)/lib

BOARD_TAG   = nano
BOARD_SUB   = atmega328

include /usr/local/opt/arduino-mk/Arduino.mk
